### ISSUE TITLE
Allow passing arn for iam role

### ISSUE THREAD

**Issue by Fliko** [serverless-components/AwsLambda#10]
Where I work I do not have the permissions to create or modify roles. When messing around with components I needed to pull down this repo and modify it so that I could pass in an existing role. Would you be open to me creating a pr allowing existing roles to be used?

**Comment by Fliko** [comment]
Since there is an existing role field this could look like
```
inputs:
    name: my-function
    description: My Serverless Function
    memory: 128
    timeout: 20
    code: ./code
    handler: handler.hello
    runtime: nodejs8.10
    role:
      arn: XXX
```
