### ISSUE TITLE
Add support for optional name input

### ISSUE THREAD

**Issue by jonathanmv** [serverless-components/AwsLambda#11]
The `name` property gets a random id while the `description` and other fields get the right value.

```
#serverless.yml
myFunction:
  component: "@serverless/aws-lambda"
  inputs:
    name: my-function
    description: Searches videos within a location
    ....
```

Is there a different way I should set the lambda function name?
