### ISSUE TITLE
Are layers actually supposed to work?

### ISSUE THREAD

**Issue by jedfoster** [serverless-components/AwsLambda#35]
I'm trying to add a layer to my lambda, but the following doesn't appear to have any effect:

```yaml
  component: '@serverless/aws-lambda'
  inputs:
    code: ./
    handler: handler.info
    description: Info endpoint for ${name}
    region: us-west-2
    runtime: nodejs12.x
    layers:
      - arn:aws:lambda:us-west-2:XXXXXXXXX:layer:commoncode:1
```

The layer already exists, but it isn't being added to lambda.
