### ISSUE TITLE
Management of secrets in this component

### ISSUE THREAD

**Issue by harleyguru** [serverless-components/AwsLambda#40]
We can use ${ssm:} syntax in serverless framework, but I can't find the way to do it with this component.
I found out parameter-store component, but it doesn't work ever.

**Comment by mwawrusch** [comment]
I think the idea behind it is to use aws parameter store to get the parameters from SMS into the serverless and reference those:

```
component: aws-parameter-store
org: XXXX
app: YYYYYY
name: issuer-sms-parameters
stage: prod

inputs:
  parameters:
    - name: dbIssuerKey
      path: /prod/faunadb/issuer/key
```

And you should be able to reference those as ${output:issuer-sms-parameters.dbIssuerKey}
Note I haven't tried the latter part so there might be a syntax discrepancy in it.
